Lang: 
  select_items: [zh_CN, en_US, $locale$]

DevicePaddle: 
  select_items: [cpu]

DeviceTorch: 
  select_items: [cpu, gpu, auto]

CaptureMode:
  select_items: [fast]
  conceal: true

InteractionMode:
  select_items: [Desktop]
  conceal: true

Resin: 
  select_items: [20,40]

BlossomType:
  select_items: [Wealth, Revelation]

DomainName:
  special_index: $INPUT_VERIFY$#domain_name

CloudGenshin:
  conceal: true

CheckImport:
  conceal: true

Python32Path:
  conceal: true

UsingAlphaChannel:
  conceal: true

RecordPath_CollectionType:
  select_items:
  - Plant
  - Artifact


